#!/usr/bin/env zsh
# Ansible vault password, read from the macOS login Keychain.
# Provisioning:
#   op read "op://Homelab/Ansible/vault password" | \
#     xargs -I{} security add-generic-password -U -s ansible-vault-homelab -a "$USER" -w {}
# Rotate: re-run the provisioning command.
security find-generic-password -s 'ansible-vault-homelab' -a "$USER" -w
